### ISSUE TITLE
'our online tool' link is broken 

### ISSUE THREAD

**Issue by rebeccawilliams** [opencivicdata/opencivicdata.org#13]
is this the same as #10?

When I click:
![screen shot 2014-11-06 at 1 03 59 pm](https://cloud.githubusercontent.com/assets/1725454/4940943/4f09efdc-65df-11e4-825b-f231c90da72a.png)
I get:

![screen shot 2014-11-06 at 1 02 42 pm](https://cloud.githubusercontent.com/assets/1725454/4940946/53cbd1d4-65df-11e4-855c-1107ff30eb7e.png)

If this could be fixed before Thanksgiving that would be ideal. cc @jamesturk @paultag

**Comment by jpmckinney** [comment]
Feature is gone now.
