### ISSUE TITLE
upload error if you type anything in 'Source' field

### ISSUE THREAD

**Issue by rebeccawilliams** [opencivicdata/opencivicdata.org#17]
I tried both a URL and text in the `Source` field on: http://opencivicdata.org/upload/

But when I tried to upload a csv I got this error:

![screen shot 2014-11-29 at 11 53 34 am](https://cloud.githubusercontent.com/assets/1725454/5235194/b68d4ec8-77bf-11e4-9ccf-d927bd6ad057.png)

When I didn't type anything in the `Source` field, I did not get an error, but I also did not get a confirmation screen saying my upload was successful.

**Comment by jpmckinney** [comment]
Feature is gone now.
