### ISSUE TITLE
lost password retrieval results in 502 error

### ISSUE THREAD

**Issue by davidmooreppf** [opencivicdata/opencivicdata.org#21]
Seeking to access :: http://opencivicdata.org/upload/

... directs to login link, but my usual pw's didn't work w/ email drm at ppolitics.org. So from page :: 

https://login.sunlightfoundation.com/accounts/password_reset/

... entered my primary email drm aatttttt ppolitics.org, site hung and went to 502 error. 

That email is already registered, confirmed on signup page.

**Comment by jpmckinney** [comment]
Feature is gone now.
